@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Pasien *</label><select name="patient_id" class="form-select" required><option value="">— Pilih —</option>@foreach($patients as $p)<option value="{{ $p->id }}" @selected(old('patient_id',$claim?->patient_id)==$p->id)>{{ $p->name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Pembayaran terkait</label><select name="payment_id" class="form-select"><option value="">— Pilih —</option>@foreach($payments as $p)<option value="{{ $p->id }}" @selected(old('payment_id',$claim?->payment_id)==$p->id)>#{{ $p->id }} - {{ $p->amount ?? 0 }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Provider *</label><input name="insurance_provider" class="form-control" value="{{ old('insurance_provider', $claim?->insurance_provider) }}" required></div>
    <div class="col-md-6"><label class="form-label">No. Polis</label><input name="policy_number" class="form-control" value="{{ old('policy_number', $claim?->policy_number) }}"></div>
    <div class="col-md-3"><label class="form-label">Tipe Klaim *</label><select name="claim_type" class="form-select">@foreach(['outpatient'=>'Rawat Jalan','inpatient'=>'Rawat Inap','emergency'=>'IGD','maternity'=>'Persalinan'] as $k=>$l)<option value="{{ $k }}" @selected(old('claim_type',$claim?->claim_type)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Tgl Pelayanan *</label><input type="date" name="service_date" class="form-control" value="{{ old('service_date', $claim?->service_date?->format('Y-m-d')) }}" required></div>
    <div class="col-md-3"><label class="form-label">Tgl Klaim *</label><input type="date" name="claim_date" class="form-control" value="{{ old('claim_date', $claim?->claim_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></div>
    @if($claim)<div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['draft','submitted','approved','rejected','paid'] as $s)<option value="{{ $s }}" @selected(old('status',$claim->status)===$s)>{{ ucfirst($s) }}</option>@endforeach</select></div>@endif
    <div class="col-md-4"><label class="form-label">Kode Diagnosis (ICD-10)</label><input name="diagnosis_code" class="form-control" value="{{ old('diagnosis_code', $claim?->diagnosis_code) }}"></div>
    <div class="col-md-8"><label class="form-label">Diagnosis</label><input name="diagnosis_text" class="form-control" value="{{ old('diagnosis_text', $claim?->diagnosis_text) }}"></div>
    <div class="col-md-6"><label class="form-label">Jumlah Diajukan *</label><input type="number" step="0.01" name="claimed_amount" class="form-control" value="{{ old('claimed_amount', $claim?->claimed_amount ?? 0) }}" required></div>
    <div class="col-md-6"><label class="form-label">Jumlah Disetujui</label><input type="number" step="0.01" name="approved_amount" class="form-control" value="{{ old('approved_amount', $claim?->approved_amount) }}"></div>
    <div class="col-md-12"><label class="form-label">Catatan</label><textarea name="notes" rows="2" class="form-control">{{ old('notes', $claim?->notes) }}</textarea></div>
</div>
