@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
    <div class="col-md-4"><label class="form-label">Pasien *</label><select name="patient_id" class="form-select" required><option value="">— Pilih —</option>@foreach($patients as $p)<option value="{{ $p->id }}" @selected(old('patient_id',$summary?->patient_id)==$p->id)>{{ $p->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">DPJP</label><select name="doctor_id" class="form-select"><option value="">— Pilih —</option>@foreach($doctors as $d)<option value="{{ $d->id }}" @selected(old('doctor_id',$summary?->doctor_id)==$d->id)>{{ $d->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Rekam Medis</label><select name="medical_record_id" class="form-select"><option value="">— Pilih —</option>@foreach($medicalRecords as $m)<option value="{{ $m->id }}" @selected(old('medical_record_id',$summary?->medical_record_id)==$m->id)>#{{ $m->id }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">MRS *</label><input type="datetime-local" name="admission_date" class="form-control" value="{{ old('admission_date', $summary?->admission_date?->format('Y-m-d\TH:i')) }}" required></div>
    <div class="col-md-3"><label class="form-label">KRS *</label><input type="datetime-local" name="discharge_date" class="form-control" value="{{ old('discharge_date', $summary?->discharge_date?->format('Y-m-d\TH:i')) }}" required></div>
    <div class="col-md-3"><label class="form-label">Kondisi Pulang *</label><select name="discharge_condition" class="form-select">@foreach($conditions as $k=>$l)<option value="{{ $k }}" @selected(old('discharge_condition',$summary?->discharge_condition)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Diagnosis Masuk *</label><input name="admission_diagnosis" class="form-control" value="{{ old('admission_diagnosis', $summary?->admission_diagnosis) }}" required></div>
    <div class="col-md-6"><label class="form-label">Diagnosis Pulang *</label><input name="discharge_diagnosis" class="form-control" value="{{ old('discharge_diagnosis', $summary?->discharge_diagnosis) }}" required></div>
    <div class="col-md-12"><label class="form-label">Keluhan Utama</label><textarea name="chief_complaint" rows="2" class="form-control">{{ old('chief_complaint', $summary?->chief_complaint) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Riwayat Penyakit</label><textarea name="history" rows="2" class="form-control">{{ old('history', $summary?->history) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Pemeriksaan Fisik</label><textarea name="physical_exam" rows="2" class="form-control">{{ old('physical_exam', $summary?->physical_exam) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Pemeriksaan Penunjang</label><textarea name="investigations" rows="2" class="form-control">{{ old('investigations', $summary?->investigations) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Tindakan & Terapi</label><textarea name="treatment" rows="2" class="form-control">{{ old('treatment', $summary?->treatment) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Perjalanan Penyakit</label><textarea name="progress" rows="2" class="form-control">{{ old('progress', $summary?->progress) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Obat Pulang</label><textarea name="discharge_medication" rows="2" class="form-control">{{ old('discharge_medication', $summary?->discharge_medication) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Anjuran / Kontrol</label><textarea name="follow_up" rows="2" class="form-control">{{ old('follow_up', $summary?->follow_up) }}</textarea></div>
</div>
