@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
    <div class="col-md-4"><label class="form-label">Jenis Insiden *</label><select name="incident_type" class="form-select" required>@foreach($types as $k=>$l)<option value="{{ $k }}" @selected(old('incident_type', $incident?->incident_type)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Severity *</label><select name="severity" class="form-select" required>@foreach(['none'=>'None','minor'=>'Minor','moderate'=>'Moderate','major'=>'Major','catastrophic'=>'Catastrophic'] as $k=>$l)<option value="{{ $k }}" @selected(old('severity', $incident?->severity)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['reported'=>'Dilaporkan','investigating'=>'Investigasi','closed'=>'Selesai'] as $k=>$l)<option value="{{ $k }}" @selected(old('status', $incident?->status ?? 'reported')===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Pasien (jika terkait)</label><select name="patient_id" class="form-select"><option value="">— Tidak terkait pasien —</option>@foreach($patients as $p)<option value="{{ $p->id }}" @selected(old('patient_id', $incident?->patient_id)==$p->id)>{{ $p->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Tgl Kejadian *</label><input type="datetime-local" name="occurred_at" class="form-control" value="{{ old('occurred_at', $incident?->occurred_at?->format('Y-m-d\TH:i') ?? now()->format('Y-m-d\TH:i')) }}" required></div>
    <div class="col-md-3"><label class="form-label">Tgl Lapor</label><input type="datetime-local" name="reported_at" class="form-control" value="{{ old('reported_at', $incident?->reported_at?->format('Y-m-d\TH:i')) }}"></div>
    <div class="col-md-12"><label class="form-label">Lokasi *</label><input name="location" class="form-control" value="{{ old('location', $incident?->location) }}" required></div>
    <div class="col-md-12"><label class="form-label">Deskripsi Kejadian *</label><textarea name="description" rows="3" class="form-control" required>{{ old('description', $incident?->description) }}</textarea></div>
    <div class="col-md-12"><label class="form-label">Tindakan Segera</label><textarea name="immediate_action" rows="2" class="form-control">{{ old('immediate_action', $incident?->immediate_action) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Akar Masalah (RCA)</label><textarea name="root_cause" rows="3" class="form-control">{{ old('root_cause', $incident?->root_cause) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Tindakan Korektif</label><textarea name="corrective_action" rows="3" class="form-control">{{ old('corrective_action', $incident?->corrective_action) }}</textarea></div>
</div>
