@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Alat *</label><select name="asset_id" class="form-select" required><option value="">— Pilih —</option>@foreach($assets as $a)<option value="{{ $a->id }}" @selected(old('asset_id', $maintenance?->asset_id)==$a->id)>{{ $a->name }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Tipe *</label><select name="maintenance_type" class="form-select">@foreach(['preventive'=>'Preventif','corrective'=>'Korektif','calibration'=>'Kalibrasi','inspection'=>'Inspeksi'] as $k=>$l)<option value="{{ $k }}" @selected(old('maintenance_type', $maintenance?->maintenance_type)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['scheduled'=>'Terjadwal','in_progress'=>'Berlangsung','done'=>'Selesai','cancelled'=>'Batal'] as $k=>$l)<option value="{{ $k }}" @selected(old('status', $maintenance?->status ?? 'scheduled')===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Tgl Jadwal *</label><input type="date" name="scheduled_date" class="form-control" value="{{ old('scheduled_date', $maintenance?->scheduled_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></div>
    <div class="col-md-3"><label class="form-label">Tgl Dilaksanakan</label><input type="date" name="performed_date" class="form-control" value="{{ old('performed_date', $maintenance?->performed_date?->format('Y-m-d')) }}"></div>
    <div class="col-md-3"><label class="form-label">Tgl Berikutnya</label><input type="date" name="next_due_date" class="form-control" value="{{ old('next_due_date', $maintenance?->next_due_date?->format('Y-m-d')) }}"></div>
    <div class="col-md-3"><label class="form-label">Biaya</label><input type="number" step="0.01" name="cost" class="form-control" value="{{ old('cost', $maintenance?->cost ?? 0) }}"></div>
    <div class="col-md-6"><label class="form-label">Pelaksana</label><input name="performer" class="form-control" value="{{ old('performer', $maintenance?->performer) }}"></div>
    <div class="col-md-6"><label class="form-label">Hasil</label><select name="result" class="form-select"><option value="">—</option>@foreach(['ok'=>'OK','needs_repair'=>'Perlu Perbaikan','replaced'=>'Diganti','failed'=>'Gagal'] as $k=>$l)<option value="{{ $k }}" @selected(old('result', $maintenance?->result)===$k)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-12"><label class="form-label">Deskripsi</label><textarea name="description" rows="2" class="form-control">{{ old('description', $maintenance?->description) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Temuan</label><textarea name="findings" rows="2" class="form-control">{{ old('findings', $maintenance?->findings) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Tindakan</label><textarea name="action" rows="2" class="form-control">{{ old('action', $maintenance?->action) }}</textarea></div>
</div>
